[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

[colors.selection]
text = '#cdd6f4'
background = '#734226'

[colors.cursor]
text = '#1e1e2e'
cursor = '#fab387'

[colors.normal]
black   = '#181825'
red     = '#ff7972'
green   = '#93fa7d'
yellow  = '#ffe572'
blue    = '#ed9c6a'
magenta = '#733712'
cyan    = '#fab387'
white   = '#fff5ef'

[colors.bright]
black   = '#a29a96'
red     = '#ffa39f'
green   = '#b5ffa5'
yellow  = '#ffefa5'
blue    = '#ffc19b'
magenta = '#ffccac'
cyan    = '#ffdeca'
white   = '#fffbf8'
