-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'


-- Hyprland Configuration

-- https://wiki.hypr.land/Configuring/

-- ==================

-- MONITOR CONFIG

-- ==================

-- Monitors from existing configuration

-- monitor=,preferred,auto,auto

--monitor = eDP-1, 1920x1080, auto, 1

hl.monitor({
    output   = "DP-2",
    mode     = "2560x1440@143.97",
    position = "auto",
    scale    = 1,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080",
    position = "auto-left",
    scale    = 1,
    transform = 3,
})

hl.monitor({
    output   = "HDMI-A-2",
    mode     = "2560x1440@120",
    position = "auto-right",
    scale    = 1,
})

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- ==================

-- STARTUP APPS

-- ==================


local hs = require("hyprsplit")


-- source = ~/.config/hypr/myColors.conf

-- source = ~/.config/hypr/workspaces.conf

-- ===============

-- VARIABLES

-- ===============

-- ==================

-- INPUT CONFIG

-- ==================

hl.config({
    input = {
        kb_layout = "fi",
        numlock_by_default = true,
        follow_mouse = 1,
        mouse_refocus = false,
        sensitivity = -0.4,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.device({
    name = "elan0511:01-04f3:303f-touchpad",
    sensitivity = 0.15,
})

hl.config({
    debug = {
        disable_logs = false,
    },
})

-- ==================

-- GENERAL LAYOUT

-- ==================

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 3,
        border_size = 5,
        -- off in niri
        resize_on_border = false,
        layout = "scrolling",
        col = {
            active_border = "rgba(fab387ff)",
            inactive_border = "rgba(595959ff)",
        },
    },
})

-- ==================

-- DECORATION

-- ==================

hl.config({
    decoration = {
        rounding = 2,
        active_opacity = 1.0,
        --inactive_opacity = 0.85
        shadow = {
            enabled = false,
            range = 4,
            render_power = 5,
            offset = "0 5",
            color = "rgba(00000070)",
        },
    },
})

-- ==================

-- ANIMATIONS

-- ==================

hl.config({
    animations = {
        enabled = true,
    },
})

-- ==================

-- LAYOUTS

-- ==================

hl.config({
    master = {
        mfact = 0.5,
    },
})

hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
        column_width = 0.5,
        focus_fit_method = 1,
        follow_focus = true,
        explicit_column_widths = "0.2, 0.333, 0.5, 0.667, 0.900, 1.0",
        -- follow_min_visible = 0.0
    },
})

-- ==================

-- MISC

-- ==================

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        vrr = 1,
        middle_click_paste = false,
    },
})

-- ==================

-- WINDOW RULES

-- ==================

hl.window_rule({
    name  = "match_class___org__w",
    match = {
        class = "tile true",
    },
    -- TODO: review rule: "match:class ^(org\\.wezfurlong\\.wezterm)$"
})

hl.window_rule({
    name  = "match_class___org__g",
    match = {
        class = "rounding=12",
    },
    -- TODO: review rule: "match:class ^(org\\.gnome\\.)"
})

hl.window_rule({
    name  = "match_class___org__g",
    match = {
    },
    -- TODO: review rule: "match:class ^(org\\.gnome\\.) border_size=0"
})

hl.window_rule({
    name  = "match_class___gnome-",
    match = {
        class = "tile=true",
    },
    -- TODO: review rule: "match:class ^(gnome-control-center)$"
})

hl.window_rule({
    name  = "match_class___pavuco",
    match = {
        class = "tile=true",
    },
    -- TODO: review rule: "match:class ^(pavucontrol)$"
})

hl.window_rule({
    name  = "match_class___nm-con",
    match = {
        class = "tile=true",
    },
    -- TODO: review rule: "match:class ^(nm-connection-editor)$"
})

hl.window_rule({
    name  = "match_class___gnome-",
    match = {
        class = "float=true",
    },
    -- TODO: review rule: "match:class ^(gnome-calculator)$"
})

hl.window_rule({
    name  = "match_class___galcul",
    match = {
        class = "float=true",
    },
    -- TODO: review rule: "match:class ^(galculator)$"
})

hl.window_rule({
    name  = "match_class___bluema",
    match = {
        class = "float=true",
    },
    -- TODO: review rule: "match:class ^(blueman-manager)$"
})

hl.window_rule({
    name  = "match_class___org__g",
    match = {
        class = "float=true",
    },
    -- TODO: review rule: "match:class ^(org\\.gnome\\.Nautilus)$"
})

--windowrule = match:class ^(steam)$, float = true

hl.window_rule({
    name  = "match_class___xdg-de",
    match = {
        class = "float=true",
    },
    -- TODO: review rule: "match:class ^(xdg-desktop-portal)$"
})

hl.window_rule({
    name  = "match_class___org__w",
    match = {
        class = "border_size=0",
    },
    -- TODO: review rule: "match:class ^(org\\.wezfurlong\\.wezterm)$"
})

hl.window_rule({
    name  = "match_class___kitty_",
    match = {
        class = "border_size=0",
    },
    -- TODO: review rule: "match:class ^(Kitty)$"
})

hl.window_rule({
    name  = "match_class___zen__",
    match = {
        class = "border_size=0",
    },
    -- TODO: review rule: "match:class ^(zen)$"
})

hl.window_rule({
    name  = "match_class___com__m",
    match = {
        class = "border_size=0",
    },
    -- TODO: review rule: "match:class ^(com\\.mitchellh\\.ghostty)$"
})

hl.window_rule({
    name  = "match_class___kitty_",
    match = {
        class = "border_size=0",
    },
    -- TODO: review rule: "match:class ^(kitty)$"
})

hl.window_rule({
    name  = "match_class___firefo",
    match = {
        class = "title ^(Picture-in-Picture)$",
    },
    -- TODO: review rule: "match:class ^(firefox)$"
})

hl.window_rule({
    name  = "match_class___zoom__",
    match = {
        class = "float=true",
    },
    -- TODO: review rule: "match:class ^(zoom)$"
})

-- DMS windows floating by default

hl.window_rule({
    name  = "match_class___org_qu",
    match = {
        class = "float=true",
    },
    -- TODO: review rule: "match:class ^(org.quickshell)$"
})

hl.window_rule({
    name  = "opacity_0_9_0_9",
    match = {
        class = "float=false",
    },
    opacity = "0.9 0.9",
})

--layerrule = noanim, ^(quickshell)$

-- source = ~/.config/hypr/windowRules.conf -> requires manual conversion
-- local windowRules = require("windowRules")
-- TODO: convert ~/.config/hypr/windowRules.conf to .lua and use require()

-- ==================

-- KEYBINDINGS

-- ==================

local mod = "SUPER"

-- === Application Launchers ===

hl.bind(mod .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "Return", hl.dsp.exec_cmd("alacritty"))

hl.bind(mod .. " + " .. "space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))

hl.bind(mod .. " + " .. "V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"))

hl.bind("CTRL + SHIFT" .. " + " .. "escape", hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"))

hl.bind(mod .. " + " .. "comma", hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"))

hl.bind(mod .. " + " .. "N", hl.dsp.exec_cmd("dms ipc call notifications toggle"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("dms ipc call notepad toggle"))

hl.bind(mod .. " + " .. "Y", hl.dsp.exec_cmd("dms ipc call dankdash wallpaper"))

hl.bind(mod .. " + " .. "TAB", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))

hl.bind(mod .. " + " .. "B", hl.dsp.exec_cmd("zen-browser"))

hl.bind(mod .. " + " .. "U", hl.dsp.exec_cmd("unityhub"))

hl.bind("ALT" .. " + " .. "Tab", hl.dsp.focus({ workspace = "previous" }))

-- === Cheat sheet

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "Slash", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"))

-- === Security ===

hl.bind(mod .. " + " .. "ALT" .. " + " .. "L", hl.dsp.exec_cmd("dms ipc call lock lock"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exit())

hl.bind("CTRL + ALT" .. " + " .. "Delete", hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"))

-- === Audio Controls ===

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 3"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 3"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("dms ipc call audio micmute"), { locked = true })

-- === Brightness Controls ===

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("dms ipc call brightness increment 5"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5"), { locked = true })

-- === Window Management ===

hl.bind(mod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "T", hl.dsp.window.float())

hl.bind(mod .. " + " .. "W", hl.dsp.group.toggle())

-- === Focus Navigation ===


hl.bind(mod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind(mod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))


hl.bind(mod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

hl.bind(mod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))


-- === Window Movement ===


hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "left" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "down" }))
hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "up" }))
hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "period", hl.dsp.layout("promote"))



-- === Column Navigation ===

hl.bind(mod .. " + " .. "Home", hl.dsp.focus({ window = "first" }))

hl.bind(mod .. " + " .. "End", hl.dsp.focus({ window = "last" }))

-- === Monitor Navigation ===

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

-- === Move to Monitor ===

hl.bind(mod .. " + " .. "SHIFT + CTRL" .. " + " .. "left", hl.dsp.window.move({ monitor = "-1" }))

hl.bind(mod .. " + " .. "SHIFT + CTRL" .. " + " .. "down", hl.dsp.window.move({ monitor = "-1" }))

hl.bind(mod .. " + " .. "SHIFT + CTRL" .. " + " .. "up", hl.dsp.window.move({ monitor = "+1" }))

hl.bind(mod .. " + " .. "SHIFT + CTRL" .. " + " .. "right", hl.dsp.window.move({ monitor = "+1" }))

hl.bind(mod .. " + " .. "SHIFT + CTRL" .. " + " .. "H", hl.dsp.window.move({ monitor = "-1" }))

hl.bind(mod .. " + " .. "SHIFT + CTRL" .. " + " .. "J", hl.dsp.window.move({ monitor = "-1" }))

hl.bind(mod .. " + " .. "SHIFT + CTRL" .. " + " .. "K", hl.dsp.window.move({ monitor = "+1" }))

hl.bind(mod .. " + " .. "SHIFT + CTRL" .. " + " .. "L", hl.dsp.window.move({ monitor = "+1" }))

-- === Workspace Navigation ===

hs.config({ num_workspaces = 10 })
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind("SUPER + " .. key, hs.dsp.focus({ workspace = i }))
    hl.bind("SUPER + SHIFT + " .. key, hs.dsp.window.move({ workspace = i, follow = false }))
end

hl.bind("SUPER + " .. "g", hs.dsp.grab_rogue_windows())

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + Page_Down", hl.dsp.split:workspace("e+1"))

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + Page_Up", hl.dsp.split:workspace("e-1"))

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + U", hl.dsp.split:workspace("e+1"))

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + I", hl.dsp.split:workspace("e-1"))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + CTRL + down", hl.dsp.split:movetoworkspace("e+1"))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + CTRL + up", hl.dsp.split:movetoworkspace("e-1"))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + CTRL + U", hl.dsp.split:movetoworkspace("e+1"))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + CTRL + I", hl.dsp.split:movetoworkspace("e-1"))

-- === Move Workspaces ===

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + Page_Down", hl.dsp.split:movetoworkspace("e+1"))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + Page_Up", hl.dsp.split:movetoworkspace("e-1"))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + U", hl.dsp.split:movetoworkspace("e+1"))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + I", hl.dsp.split:movetoworkspace("e-1"))

-- Move workspace to monitor in direction

-- bind = $mod CTRL ALT, left, moveworkspacetomonitor, l

-- bind = $mod CTRL ALT, right, moveworkspacetomonitor, r

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- === Mouse Wheel Navigation ===

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + mouse_down", hl.dsp.split:workspace("e-1"))

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + mouse_up", hl.dsp.split:workspace("e+1"))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + CTRL + mouse_down", hl.dsp.split:movetoworkspace("e+1"))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + CTRL + mouse_up", hl.dsp.split:movetoworkspace("e-1"))

-- === Numbered Workspaces ===

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + 1", hl.dsp.split:workspace(1))

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + 2", hl.dsp.split:workspace(2))

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + 3", hl.dsp.split:workspace(3))

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + 4", hl.dsp.split:workspace(4))

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + 5", hl.dsp.split:workspace(5))

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + 6", hl.dsp.split:workspace(6))

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + 7", hl.dsp.split:workspace(7))

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + 8", hl.dsp.split:workspace(8))

-- TODO: manual review (unknown dispatcher: split:workspace)
-- hl.bind("$mod + 9", hl.dsp.split:workspace(9))

-- === Move to Numbered Workspaces ===

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + 1", hl.dsp.split:movetoworkspace(1))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + 2", hl.dsp.split:movetoworkspace(2))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + 3", hl.dsp.split:movetoworkspace(3))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + 4", hl.dsp.split:movetoworkspace(4))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + 5", hl.dsp.split:movetoworkspace(5))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + 6", hl.dsp.split:movetoworkspace(6))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + 7", hl.dsp.split:movetoworkspace(7))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + 8", hl.dsp.split:movetoworkspace(8))

-- TODO: manual review (unknown dispatcher: split:movetoworkspace)
-- hl.bind("$mod + SHIFT + 9", hl.dsp.split:movetoworkspace(9))

-- === Column Management ===

hl.bind(mod .. " + " .. "bracketleft", hl.dsp.layout("preselect l"))

hl.bind(mod .. " + " .. "bracketright", hl.dsp.layout("preselect r"))

-- === Sizing & Layout ===

hl.bind(mod .. " + " .. "G", hl.dsp.layout("togglesplit"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + CTRL + F", hl.dsp.resizeactive("exact 100%"))

-- === Move/resize windows with mainMod + LMB/RMB and dragging ===

-- hl.bind(mod .. " + " .. "mouse:272", nil, { mouse = true })

hl.bind(mod .. " + " .. "mouse:273", hl.dsp.window.resize(nil), { mouse = true })

-- === Move/resize windows with mainMod + LMB/RMB and dragging ===

-- TODO: manual review (unknown dispatcher: Expand window left)
-- hl.bind("$mod + code:20", hl.dsp.Expand window left("resizeactive", "-100 0"))

-- TODO: manual review (unknown dispatcher: Shrink window left)
-- hl.bind("$mod + code:21", hl.dsp.Shrink window left("resizeactive", "100 0"))

-- === Manual Sizing ===

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + ALT + End", hl.dsp.resizeactive("-10% 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + ALT + Home", hl.dsp.resizeactive("10% 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + ALT + Prior", hl.dsp.resizeactive("0 -10%"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + ALT + Next", hl.dsp.resizeactive("0 10%"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + ALT + Left", hl.dsp.resizeactive("-10% 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + ALT + Right", hl.dsp.resizeactive("10% 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + ALT + Up", hl.dsp.resizeactive("0 -10%"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + ALT + Down", hl.dsp.resizeactive("0 10%"))

hl.bind(mod .. " + " .. "ALT" .. " + " .. "Left", hl.dsp.layout("colresize -conf"))

hl.bind(mod .. " + " .. "ALT" .. " + " .. "Right", hl.dsp.layout("colresize +conf"))

hl.bind(mod .. " + " .. "E", hl.dsp.layout("colresize 1.0"))

hl.bind(mod .. " + " .. "X", hl.dsp.layout("colresize +conf"))

-- === Screenshots ===

hl.bind("Print", hl.dsp.exec_cmd("dms screenshot"))

hl.bind("CTRL" .. " + " .. "Print", hl.dsp.exec_cmd("dms screenshot full"))

hl.bind("ALT" .. " + " .. "Print", hl.dsp.exec_cmd("dms screenshot window"))

-- === System Controls ===

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.dpms("toggle"))

hl.bind(mod .. " + " .. "I", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"))

hl.bind(mod .. " + " .. "P", hl.dsp.exec_cmd("dms ipc call notepad toggle"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "C", hl.dsp.exec_cmd("kitty -e bash -c 'hyprctl clients -j; echo Press any key to exit.. ; read -n1'"))

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("bash -c wl-paste --watch cliphist store &")
    hl.exec_cmd("hyprpm reload -n")
end)
