
 #Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
 #"Smart gaps" / "No gaps when only"
 #uncomment all if you wish to use that.
 workspace = w[tv1], gapsout:0, gapsin:0
 workspace = f[1], gapsout:0, gapsin:0


 windowrule {
     name = no-gaps-wtv1
     match:float = false
     match:workspace = w[tv1]

     border_size = 0
     rounding = 0
 }

 windowrule {
     name = no-gaps-f1
     match:float = false
     match:workspace = f[1]

     border_size = 0
     rounding = 0
 }

 windowrule {
 	name = secret-highlight
	match:workspace = s[true]
	border_size = 6
	rounding = 4
	border_color = rgba(ff11ffee) rgba(aaffffee) 45deg;
 }

windowrule {
	name = steam-rules
  match:class = steam
  #workspace = 21
  opacity = 0.8
}

windowrule {
  name = discord-rules
  match:class = discord
  opacity = 0.8

  #workspace = 20
}

windowrule {
  name = kitty-rules
  match:class = kitty
  opacity = 0.9 0.85

}

# windowrule {
#	name = unity
#	match:class = Unity
#	workspace = 2
#}

 # windowrule {
	# name = unity-floating
	# match:class = Unity
	# match:float = true
	# workspace = 2 silent
	# no_initial_focus = on
 # }

 #windowrulev2 = workspace special:gamescope, class:^(?i)gamescope$

#windowrulev2 = minsize 230 200, initialTitle:(UnityEditor.AddComponent.AddComponentWindow), no_initial_focus: false, workspace: 2
#windowrulev2 = minsize 300 200, initialTitle:(UnityEditor.IMGUI.Controls.AdvancedDropdownWindow), no_initial_focus: false, workspace: 2
#windowrulev2 = minsize 230 200, initialTitle:(UnityEditor.Rendering.FilterWindow), no_initial_focus: false, workspace: 2
#windowrulev2 = minsize 300 200, initialTitle:(UnityEditor.LayerVisibilityWindow), no_initial_focus: false, workspace: 2
#windowrulev2 = minsize 230 500, initialTitle:(UnityEditor.AnnotationWindow), no_initial_focus: false, workspace: 2
#windowrulev2 = minsize 150 300, initialTitle:(UnityEditor.PopupWindow), no_initial_focus: false, workspace: 2
#windowrulev2 = minsize 500 350, initialTitle:(Select Preset...), no_initial_focus: false, workspace: 2
#windowrulev2 = minsize 300 100, initialTitle:(UnityEditor.Snap.GridSettingsWindow), no_initial_focus: false, workspace: 2
#windowrulev2 = minsize 500 500, initialTitle:(UnityEngine.InputSystem.Editor.AdvancedDropdownWindow), no_initial_focus: false, workspace: 2


