workspace = 1, monitor:1, persistent:true, default:true
workspace = 2, monitor:1, defaultName:Unity
workspace = 3, monitor:1, defaultName:Rider
workspace = 21, monitor:2, persistent:true, defaultName:Steam
workspace = 20, monitor:0, persistent:true, defaultName:Discord
