cursor #cdd6f4
cursor_text_color #a6adc8

foreground            #cdd6f4
background            #1e1e2e
selection_foreground  #1e1e2e
selection_background  #f9e2af
url_color             #fab387

color0   #181825
color1   #ff7972
color2   #93fa7d
color3   #ffe572
color4   #ed9c6a
color5   #733712
color6   #fab387
color7   #fff5ef
color8   #a29a96
color9   #ffa39f
color10  #b5ffa5
color11  #ffefa5
color12  #ffc19b
color13  #ffccac
color14  #ffdeca
color15  #fffbf8
