cursor #cdd6f4
cursor_text_color #a6adc8

foreground            #cdd6f4
background            #181825
selection_foreground  #1e1e2e
selection_background  #f9e2af
url_color             #fab387

color0   #181825
color1   #e34b81
color2   #98d66e
color3   #dbac7b
color4   #be7040
color5   #bb9076
color6   #fab387
color7   #abb2bf
color8   #5c6370
color9   #e05f91
color10  #aae086
color11  #e8c197
color12  #ffc496
color13  #b36754
color14  #987450
color15  #ffffff
